info:
  title: Enrolled Application Discovery
  version: 0.0.0
  description: standard for sharing application enrolement data
openapi: 3.0.0
paths:
  /.well-known/public-applications:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list'
          description: OK
components:
  schemas:
    list:
      type: "object"
      required:
        - "count"
        - "publisher"
        - "results"
      properties:
        count:
          type: integer
        next:
          type: string
        previous:
          type: string
        publisher:
          $ref: '#/components/schemas/publisher'
        results:
          type: array
          items:
            $ref: '#/components/schemas/application'
    publisher:
      type: "object"
      required:
        - "organization"
        - "api_endpoint"
      properties:
        organization:
          type: string
        endpoints:
          type: array
          items:
            $ref: "#/components/schemas/endpoint"
        contacts:
          type: array
          items:
            $ref: "#/components/schemas/contact_point"
        logo_url:
          type: string
          format: uri
    application:
      type: "object"
      required:
        - "name"
        - "description"
      properties:
        name:
          type: string
          description: "Application Name"
        description:
          type: string
        uri:
          type: string
          format: uri
        logo_uri:
          type: string
          format: uri
        logo_allowed_user:
          type: string
        tos_uri:
          type: string
          format: uri
          description: "Link to the application's terms of service."
        privacy_policy_uri:
          type: string
          format: uri
          description: "Link to the application's privacy policy."
        contacts:
          type: array
          items:
            $ref: "#/components/schemas/contact_point"
    contact_point:
      type: object
      required:
        - "system"
        - "value"
      properties:
        system:
          type: string
          enum:
            - "phone"
            - "fax"
            - "email"
            - "pager"
            - "url"
            - "sms"
            - "other"
        value:
          type: string
    endpoint:
      type: object
      required:
        - "name"
        - "address"
      properties:
        name:
          type: string
        address:
          type: string
          format: uri
      